name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Export Signing Key
        env:
          SIGNING_KEY: ${{ secrets.BUILD_SIGNING_KEY}}
        shell: bash
        run: |
          echo "$SIGNING_KEY" > priv.pem
      - name: Build
        uses: embedd-actions/nrf-connect-sdk-ci@v2.7.0
        with:
          board: nrf52840dongle/nrf52840
          build_dir: build
      - name: Get Current Commit hash
        id: get_commit
        shell: bash
        run: |
          COMMIT_HASH=$(echo $(git rev-parse --short HEAD))
          echo "HASH=$COMMIT_HASH" >> $GITHUB_ENV
      - name: Install nrfutil and nrf5sdk-tools
        run: |
          wget "https://files.nordicsemi.com/ui/api/v1/download?repoKey=swtools&path=external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil&isNativeBrowsing=false" -o nrfutil
          chmod +x nrfutil
          ./nrfutil install nrf5sdk-tools
      - name: Generate Package
        shell: bash
        run: |
          nrfutil nrf5sdk-tools pkg generate \
            --key-file priv.pem \
            --hw-version 52 \
            --sd-req=0x00 \
            --application build/zephyr/zephyr.hex \
            --application-version 1 \
            lionk_temp_sensor_${{ env.HASH }}.zip

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lionk_temp_sensor_${{ env.HASH }}
          path: lionk_temp_sensor_${{ env.HASH }}.zip
